-- ============================================================================
-- 002_personal_os_expansion.sql — Phase 1 v1 expansion
-- Created: 2026-05-04
-- Author: Sarah (chief of staff)
--
-- Adds 8 tables + 3 views for the expanded Personal OS Dashboard:
--   subagent_tasks, content_items, relationship_roster, health_log,
--   idea_park, cost_telemetry, daily_tasks, pillar_state
--   + views: today_daily_tasks, pulse, active_subagents
--
-- Companion to 001_personal_os.sql (proposals, decisions, blockers,
-- running_tasks, briefings — already applied 2026-05-03).
-- ============================================================================

-- ---------------------------------------------------------------------------
-- subagent_tasks: live status + queued + Sarah-suggested tasks per project
-- Distinct from running_tasks (which is the lower-level OpenClaw process feed):
-- subagent_tasks is the human-facing "what is each agent doing for which project".
-- ---------------------------------------------------------------------------
create table if not exists public.subagent_tasks (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz default now(),
  project text not null,                   -- 'home', 'dls', 'wellness-platform', 'personal', etc.
  agent_name text,                         -- 'Builder', 'Auditor', 'Scout', 'Quill', 'Sage', 'Atlas', 'Vita'
  label text not null,
  description text,
  status text default 'queued',            -- 'queued', 'suggested', 'running', 'completed', 'failed', 'killed', 'deferred'
  source text default 'sarah-suggested',   -- 'sarah-suggested', 'agreed-on', 'christopher-requested'
  estimated_minutes int,
  started_at timestamptz,
  ended_at timestamptz,
  session_key text,                        -- maps to running_tasks.session_key when active
  rationale text,                          -- Sarah's "why this task" reasoning
  log_url text,                            -- optional deep link to live log
  metadata jsonb default '{}'::jsonb
);
create index if not exists idx_subagent_tasks_project_status
  on public.subagent_tasks(project, status, created_at desc);
create index if not exists idx_subagent_tasks_running
  on public.subagent_tasks(status)
  where status in ('running', 'queued', 'suggested');

-- ---------------------------------------------------------------------------
-- content_items: DLS posts, ads, images, letter drafts in the pipeline
-- ---------------------------------------------------------------------------
create table if not exists public.content_items (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz default now(),
  project text not null,                   -- 'dls', 'agentic-ai-content', 'climate-book', etc.
  series text,                             -- 'salem', 'titanic', 'asylum', 'raven-letters', NULL for non-series
  asset_type text not null,                -- 'social-post', 'ad-creative', 'email', 'image', 'letter-draft', 'artifact'
  platform text,                           -- 'meta', 'klaviyo', 'shopify', 'instagram', etc.
  status text default 'idea',              -- 'idea', 'drafted', 'reviewed', 'scheduled', 'published', 'rejected'
  title text not null,
  body text,                               -- copy/markdown
  image_url text,                          -- preview asset
  asset_urls jsonb default '[]'::jsonb,    -- additional images/files
  scheduled_for timestamptz,
  published_at timestamptz,
  proposal_id uuid references public.proposals(id),  -- if generated by an approved proposal
  ab_variant_group text,                   -- non-null when part of an A/B test
  performance jsonb default '{}'::jsonb,   -- post-publish stats (CTR, opens, conversions, etc.)
  metadata jsonb default '{}'::jsonb
);
create index if not exists idx_content_status
  on public.content_items(project, status, created_at desc);
create index if not exists idx_content_scheduled
  on public.content_items(scheduled_for)
  where status = 'scheduled';
create index if not exists idx_content_ab
  on public.content_items(ab_variant_group)
  where ab_variant_group is not null;

-- ---------------------------------------------------------------------------
-- relationship_roster: people Christopher cares about + cadence + last contact
-- ---------------------------------------------------------------------------
create table if not exists public.relationship_roster (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz default now(),
  name text not null,
  relationship_type text not null,         -- 'spouse', 'child', 'stepchild', 'grandchild', 'parent', 'sibling', 'friend', 'colleague'
  cadence text,                            -- 'daily', 'weekly', 'monthly', 'quarterly', 'annually'
  last_contact_at timestamptz,
  next_nudge_at timestamptz,               -- computed from cadence + last_contact (Sarah maintains this)
  birthday date,
  anniversary date,
  notes text,                              -- prior-conversation context so Sarah doesn't ask cold
  active boolean default true,
  metadata jsonb default '{}'::jsonb
);
create index if not exists idx_roster_nudge
  on public.relationship_roster(next_nudge_at)
  where active = true;
create index if not exists idx_roster_active
  on public.relationship_roster(relationship_type, active);

-- ---------------------------------------------------------------------------
-- health_log: injection, sleep, daily stack, mood for Body Man
-- Flexible value column (jsonb) so each category can have its own shape.
-- ---------------------------------------------------------------------------
create table if not exists public.health_log (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz default now(),
  log_date date not null default current_date,
  category text not null,                  -- 'injection', 'sleep', 'workout', 'protein', 'hydration', 'steps', 'mood'
  subcategory text,                        -- e.g. injection: 'testosterone', 'glow-stack', 'nad', 'vit-d'
  value jsonb not null,                    -- {"hours": 7.5} or {"dose_mg": 200, "batch": "..."} or {"sets": 3, "reps": 12}
  notes text,
  metadata jsonb default '{}'::jsonb
);
create index if not exists idx_health_date
  on public.health_log(log_date desc, category);
create index if not exists idx_health_category
  on public.health_log(category, subcategory, log_date desc);

-- ---------------------------------------------------------------------------
-- idea_park: frictionless capture inbox
-- ---------------------------------------------------------------------------
create table if not exists public.idea_park (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz default now(),
  project text,                            -- nullable; tag-by-project optional
  title text not null,
  body text,
  source text default 'dashboard',         -- 'dashboard', 'telegram', 'voice', 'sarah-surfaced'
  status text default 'parked',            -- 'parked', 'committed', 'killed', 'rotting'
  rotted_flag boolean default false,       -- set true by cron when > 90 days old + status = parked
  committed_to_project text,
  killed_reason text,
  metadata jsonb default '{}'::jsonb
);
create index if not exists idx_idea_park_status
  on public.idea_park(status, created_at desc);
create index if not exists idx_idea_park_rotting
  on public.idea_park(rotted_flag, created_at)
  where status = 'parked';

-- ---------------------------------------------------------------------------
-- cost_telemetry: API spend + service costs + per-project attribution
-- Append-only; aggregations done at query time.
-- ---------------------------------------------------------------------------
create table if not exists public.cost_telemetry (
  id uuid primary key default gen_random_uuid(),
  log_date date not null default current_date,
  vendor text not null,                    -- 'anthropic', 'openai', 'elevenlabs', 'vercel', 'render', 'supabase', 'chatgpt-pro'
  service text,                            -- 'claude-opus-4-7', 'gpt-5.1', 'tts', etc.
  project text,                            -- attribution: 'wellness', 'dls', 'personal', 'system'
  cost_usd numeric(10,4) not null,
  units int,                               -- e.g. tokens, characters, seconds
  unit_type text,                          -- 'input_tokens', 'output_tokens', 'characters', 'seconds'
  metadata jsonb default '{}'::jsonb
);
create index if not exists idx_cost_date
  on public.cost_telemetry(log_date desc, vendor);
create index if not exists idx_cost_project
  on public.cost_telemetry(project, log_date desc);

-- ---------------------------------------------------------------------------
-- daily_tasks: today's planned work for Sarah + subagents (per business tab)
-- Higher-level than subagent_tasks: a daily_task may spawn multiple subagent_tasks.
-- ---------------------------------------------------------------------------
create table if not exists public.daily_tasks (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz default now(),
  task_date date not null default current_date,
  project text not null,                   -- 'home', 'personal', 'dls', 'wellness-platform', etc.
  title text not null,
  description text,
  source text default 'sarah-suggested',   -- 'sarah-suggested', 'agreed-on', 'christopher-requested', 'recurring'
  status text default 'pending',           -- 'pending', 'approved', 'started', 'completed', 'deferred', 'killed'
  priority int default 2,                  -- 1=high, 2=normal, 3=low
  estimated_minutes int,
  started_at timestamptz,
  completed_at timestamptz,
  rationale text,
  metadata jsonb default '{}'::jsonb
);
create index if not exists idx_daily_tasks_date_project
  on public.daily_tasks(task_date desc, project, status);
-- Note: a partial index `where task_date = current_date` would be ideal but
-- current_date is not IMMUTABLE in Postgres. Use the broader date+project+status
-- index above + a filtered query at read time.
create index if not exists idx_daily_tasks_pending
  on public.daily_tasks(task_date, project)
  where status in ('pending', 'approved', 'started');

-- ---------------------------------------------------------------------------
-- pillar_state: Body Man's six-pillar status snapshot (one row per pillar)
-- Updated in place; pillar names are unique.
-- ---------------------------------------------------------------------------
create table if not exists public.pillar_state (
  id uuid primary key default gen_random_uuid(),
  pillar text not null unique,             -- 'work', 'physical', 'cognitive', 'relationships', 'hobbies', 'recovery'
  updated_at timestamptz default now(),
  status text not null default 'green',    -- 'green', 'yellow', 'red'
  summary text,                            -- 1-2 sentence current state
  last_touched_at timestamptz,             -- when this pillar last had real activity
  notes text,                              -- longer-form Sarah notes
  metadata jsonb default '{}'::jsonb
);

-- Seed the six pillars so the dashboard always has rows to render.
insert into public.pillar_state (pillar, status, summary)
values
  ('work',          'green',  'Active across DLS, Wellness, Personal OS Dashboard.'),
  ('physical',      'yellow', 'Workout protocol locked; pullup-stand + rower not yet assembled. Tuesday injection appointments active.'),
  ('cognitive',     'green',  'Daily reading + agentic-AI curriculum + learning pipeline.'),
  ('relationships', 'green',  'Daily marriage anchors active (morning coffee + evening together). Friend roster pending.'),
  ('hobbies',       'green',  'Reading, weekly hike, French press coffee, light gaming, essays.'),
  ('recovery',      'green',  '11 PM lights-out / 7 AM wake target. Bipolar mood-stability priority.')
on conflict (pillar) do nothing;

-- ---------------------------------------------------------------------------
-- VIEWS
-- ---------------------------------------------------------------------------

-- Today's daily tasks across all projects, ordered by priority then project.
create or replace view public.today_daily_tasks as
select * from public.daily_tasks
where task_date = current_date
  and status in ('pending', 'approved', 'started')
order by priority asc, project, created_at;

-- Pulse view: 30-second cockpit summary (single-row aggregation)
create or replace view public.pulse as
select
  (select count(*) from public.proposals where status = 'pending')::int                              as pending_proposals,
  (select count(*) from public.daily_tasks
     where task_date = current_date and status in ('pending','approved'))::int                       as today_tasks_open,
  (select count(*) from public.subagent_tasks where status = 'running')::int                         as agents_running,
  (select count(*) from public.blockers where resolved_at is null)::int                              as blockers_open,
  (select count(*) from public.idea_park where rotted_flag = true and status = 'parked')::int        as ideas_rotting,
  (select count(*) from public.relationship_roster
     where active = true and next_nudge_at is not null and next_nudge_at <= now() + interval '2 days')::int
                                                                                                     as relationship_nudges_due;

-- Active subagent feed (across all projects) — running first, then queued, then suggested
create or replace view public.active_subagents as
select * from public.subagent_tasks
where status in ('running', 'queued', 'suggested')
order by
  case status
    when 'running'   then 1
    when 'queued'    then 2
    when 'suggested' then 3
  end,
  created_at desc;

-- ============================================================================
-- End of 002_personal_os_expansion.sql
-- ============================================================================
